---
# Works only on RedHat
- name: Fail for other distributions
  fail:
    msg: 'Deploy to {{ ansible_os_family }} distributions is not supported yet'
  when: ansible_os_family != "RedHat"

- name: Dependencies
  include_tasks: install_dependencies.yml

- name: Install RPM for RedHat
  include_tasks: install_rpm.yml
  when: ansible_os_family == 'RedHat'

- name: Start
  include_tasks: start_instance.yml
  vars:
    instance: '{{ item }}'
  with_items: '{{ cartridge_config.instances }}'
